language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 8.0
  - nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_install:
  - sudo apt-get install -qq gawk

before_script:
  - phpize && ./configure && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0

after_failure:
  - for FILE in `find ./tests -name '*.diff'`; do echo echo $FILE; cat $FILE; echo; done
